// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHtDKX7PBV391oSCUITRi7yvOk9SybEHw',
    appId: '1:888174194718:web:beebab5f41d55acf9b7e0f',
    messagingSenderId: '888174194718',
    projectId: 'kutuphane-f4443',
    authDomain: 'kutuphane-f4443.firebaseapp.com',
    storageBucket: 'kutuphane-f4443.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2YWWxqasTESBex8xvYL7ZSW2ZEzT-yEg',
    appId: '1:888174194718:android:9a78dd13369588149b7e0f',
    messagingSenderId: '888174194718',
    projectId: 'kutuphane-f4443',
    storageBucket: 'kutuphane-f4443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj76_Sg4A6YGSitnRQVT3cCCr3YE9ubJM',
    appId: '1:888174194718:ios:e03dd4f9fff537359b7e0f',
    messagingSenderId: '888174194718',
    projectId: 'kutuphane-f4443',
    storageBucket: 'kutuphane-f4443.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj76_Sg4A6YGSitnRQVT3cCCr3YE9ubJM',
    appId: '1:888174194718:ios:e03dd4f9fff537359b7e0f',
    messagingSenderId: '888174194718',
    projectId: 'kutuphane-f4443',
    storageBucket: 'kutuphane-f4443.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
